## 파이썬 기본연습
- 본격적인 데이터 분석에 앞서 파이썬 기본 메소드 복습하기

### Numpy
- 생성
    - array
    - arange
    - ones, zeros, full
    - identity: 단위 행렬(항등 행렬) 형태, 대각선이 1이고 나머지가 0인 정사각형 행렬 생성
    - reshape


- 연산
    - abs
    - sqrt
    - square
    - exp
    - log, log10
    - sign: 원소의 부호값 반환. 양수는 1, 음수는 -1, 0은 0
    - 소수점: round, ceil, floor, trunc


- ndarray끼리 연산 (산술 연산자로 대체 가능)
    - add(배열1, 배열2), subtract, multiply, divide, mod, power
    
    
- 차원 변환
    - reshape
    - ravel, flatten: 다차원 배열을 1차원으로 평탄화
    - T, transpose: 축 교환

<b>생성</b>

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([3]*10)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
np.array('안녕하세요')

array('안녕하세요', dtype='<U5')

In [10]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [33]:
np.full((5, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.identity(5).dtype

dtype('float64')

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones(3).dtype

dtype('float64')

In [40]:
np.ones(3, dtype='int').dtype

dtype('int32')

In [43]:
threes = np.full(10, 3)

In [44]:
threes

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [45]:
threes.shape

(10,)

In [48]:
threes.size

10

In [49]:
threes.ndim

1

In [53]:
threes_2d = threes.reshape(2, 5)

In [54]:
threes_2d.ndim

2

<b>연산</b>

In [61]:
arr = np.array([-1, 0, 5, -2., -99, 1])

arr

array([ -1.,   0.,   5.,  -2., -99.,   1.])

In [64]:
np.abs(arr)

array([ 1.,  0.,  5.,  2., 99.,  1.])

In [65]:
np.sqrt(arr)

C:\Users\ing06\AppData\Local\Temp\ipykernel_304\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 0.        , 2.23606798,        nan,        nan,
       1.        ])

In [66]:
np.square(arr)

array([1.000e+00, 0.000e+00, 2.500e+01, 4.000e+00, 9.801e+03, 1.000e+00])

In [67]:
np.exp(arr)

array([3.67879441e-01, 1.00000000e+00, 1.48413159e+02, 1.35335283e-01,
       1.01122149e-43, 2.71828183e+00])

In [68]:
np.sign(arr)

array([-1.,  0.,  1., -1., -1.,  1.])

In [69]:
np.log(arr)

C:\Users\ing06\AppData\Local\Temp\ipykernel_304\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)
C:\Users\ing06\AppData\Local\Temp\ipykernel_304\3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([       nan,       -inf, 1.60943791,        nan,        nan,
       0.        ])

<b>차원 변환</b>

In [80]:
even_num = np.arange(2, 25, 2)

In [81]:
even_num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [83]:
even_num.reshape(6, -1)              # -1은 알아서 지정하라는 뜻

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24]])

In [84]:
even_num.reshape(-1, 6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [85]:
even_num.reshape(3, 2, 2)         # 3개 층, 2행 2열

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [88]:
even_num.reshape(2, 6, -1)           # 2개 층, 6행 1열

array([[[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]],

       [[14],
        [16],
        [18],
        [20],
        [22],
        [24]]])

In [89]:
even_num.reshape(-1, 6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [94]:
even_num_t = even_num.reshape(-1, 6).T
even_num_t

array([[ 2, 14],
       [ 4, 16],
       [ 6, 18],
       [ 8, 20],
       [10, 22],
       [12, 24]])

In [95]:
even_num_t.flatten()

array([ 2, 14,  4, 16,  6, 18,  8, 20, 10, 22, 12, 24])

In [96]:
even_num_t.ravel()

array([ 2, 14,  4, 16,  6, 18,  8, 20, 10, 22, 12, 24])