## 작업형 1유형

#### 1. mtcars2 데이터셋을 불러와 mpg 컬럼의 상위 10번째 값으로 상위 10개 값을 변환한 후 drat가 4이상인 값에 대해 mpg의 평균을 구하여라.

In [41]:
import pandas as pd

df = pd.read_csv('../data/기출복원/02회/mtcars2.csv')
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8    NaN  175  3.15  3.440  17.02   0   0     3     2

In [42]:
mpg_10 = df['mpg'].sort_values(ascending=False)[:10]
mpg_10

19    33.9
17    32.4
27    30.4
18    30.4
25    27.3
26    26.0
7     24.4
2     22.8
8     22.8
20    21.5
Name: mpg, dtype: float64

In [43]:
# 상위 10개값의 인덱스
mpg_idx = df['mpg'].sort_values(ascending=False)[:10].index
mpg_idx

Int64Index([19, 17, 27, 18, 25, 26, 7, 2, 8, 20], dtype='int64')

In [44]:
df['mpg'][mpg_idx]

19    33.9
17    32.4
27    30.4
18    30.4
25    27.3
26    26.0
7     24.4
2     22.8
8     22.8
20    21.5
Name: mpg, dtype: float64

In [45]:
# 시리즈에서 값만 가져옴
top_10 = df['mpg'][mpg_idx].values
top_10

array([33.9, 32.4, 30.4, 30.4, 27.3, 26. , 24.4, 22.8, 22.8, 21.5])

In [46]:
# 상위 10번째 값으로 상위 10개 값 대체
df['mpg'] = df['mpg'].replace(top_10, df['mpg'][20])

In [65]:
# drat가 4이상인 값에 대해 mpg의 평균
df = df[df['drat']>=4]
result = df['mpg'].mean()
round(result, 3)

26.743

#### 2. 앞의 데이터셋(mtcars2)을 새로 불러와 첫 번째 행부터 순서대로 80%까지의 데이터를 훈련 데이터로 추출한 후 disp 컬럼의 결측값을 disp 컬럼의 중앙값으로 대체하고 대체 전 후의 disp 변수의 표준편차 값의 차이를 구하여라. (단, 차이는 빼는 순서와 관계없이 절댓값을 취하여 표시하여라)

In [56]:
import pandas as pd

df = pd.read_csv('../data/기출복원/02회/mtcars2.csv')
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8    NaN  175  3.15  3.440  17.02   0   0     3     2

In [57]:
len(df)

32

In [58]:
ratio = len(df)*0.8
ratio

25.6

In [59]:
train = df[:int(ratio)]
train

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8    NaN  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8    NaN  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8    NaN  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8    NaN  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2

In [60]:
#  disp 컬럼의 결측값을 disp 컬럼의 중앙값으로 대체
train['disp'].isnull().sum()

4

In [61]:
no_na = train['disp'].fillna(train['disp'].median())

In [62]:
no_na.isnull().sum()

0

In [63]:
no_na.head()

0    160.0
1    160.0
2    108.0
3    258.0
4    167.6
Name: disp, dtype: float64

In [66]:
# 대체 전 후의 disp 변수의 표준편차 값의 절댓값 차이를 구하기
round(abs(train['disp'].std() - no_na.std()), 3)


7.966

#### 3. gehan 데이터셋을 불러와 time 컬럼에서 이상값의 합을 구하여라. (단 이상값은 평균에서 1.5표준편차 이상으로 벗어난 값으로 정의함)

In [67]:
import pandas as pd

df = pd.read_csv('../data/기출복원/02회/gehan.csv')

df.head()

pair  time  cens    treat
0     1     1     1  control
1     1    10     1     6-MP
2     2    22     1  control
3     2     7     1     6-MP
4     3     3     1  control

In [68]:
df['time'].isnull().sum()

0

In [69]:
# 이상값의 합
outliers = df['time'][(df['time'] < df['time'].mean()-1.5*df['time'].std()) | (df['time'] > df['time'].mean()+1.5*df['time'].std())]
outliers

5     32
15    34
17    32
31    35
Name: time, dtype: int64

In [70]:
sum(outliers)

133

## 작업형 2유형

#### 1. 주어진 데이터를 이용해 예측 모형을 만들고 아래에 따라 CSV 파일을 생성하시오. (단, 제출 전 두 개 이상의 모형의 성능을 비교하여 가장 우수한 모형을 선정할 것)

#### 환자 4,087명에 대한 학습용 데이터를 이용해 뇌줄종 여부 예측 모형을 만든 후 이를 평가용 데이터에 적용해 얻은 1,022명 환자의 뇌졸중 여부 예측값을 CSV 파일로 생성(제출한 모델의 성능은 Accuracy 평가 지표에 따라 채점)

In [177]:
import pandas as pd

X_train = pd.read_csv('../data/기출복원/02회/stroke_X_train.csv')
X_test = pd.read_csv('../data/기출복원/02회/stroke_X_test.csv')
y_train = pd.read_csv('../data/기출복원/02회/stroke_y_train.csv')
y_test = pd.read_csv('../data/기출복원/02회/stroke_y_test.csv')

In [178]:
X_train.head()

id  gender   age  hypertension  heart_disease ever_married work_type  \
0    575    Male  13.0             0              0           No  children   
1  60533  Female  23.0             0              0           No   Private   
2  11935  Female   9.0             0              0           No  children   
3  61291    Male  28.0             0              0          Yes   Private   
4  64534  Female  25.0             0              0          Yes   Private   

  Residence_type  avg_glucose_level   bmi smoking_status  
0          Rural              98.65  20.1        Unknown  
1          Rural              91.95  23.0        Unknown  
2          Rural             110.97  17.7        Unknown  
3          Rural             169.49  27.2        Unknown  
4          Urban             104.66  23.9   never smoked

In [179]:
X_test.head()

id  gender   age  hypertension  heart_disease ever_married work_type  \
0  30669    Male   3.0             0              0           No  children   
1  30468    Male  58.0             1              0          Yes   Private   
2  56543  Female  70.0             0              0          Yes   Private   
3  37893  Female  37.0             0              0          Yes   Private   
4  72911  Female  57.0             1              0          Yes   Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  
0          Rural              95.12  18.0          Unknown  
1          Urban              87.96  39.2     never smoked  
2          Rural              69.04  35.9  formerly smoked  
3          Rural              73.50  26.1  formerly smoked  
4          Rural             129.54  60.9           smokes

In [180]:
y_train.head()

id  stroke
0    575       0
1  60533       0
2  11935       0
3  61291       0
4  64534       0

In [181]:
# 결측값 확인
print(X_train.isnull().sum())
print(X_test.isnull().sum())

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  165
smoking_status         0
dtype: int64
id                    0
gender                0
age                   0
hypertension          0
heart_disease         0
ever_married          0
work_type             0
Residence_type        0
avg_glucose_level     0
bmi                  36
smoking_status        0
dtype: int64


In [182]:
# 결측값 평균으로 대체
X_train['bmi'] = X_train['bmi'].fillna(X_train['bmi'].mean())
X_test['bmi'] = X_test['bmi'].fillna(X_test['bmi'].mean())

In [183]:
print(X_train.isnull().sum())
print(X_test.isnull().sum())

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
dtype: int64
id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
dtype: int64


In [184]:
# 이상값 확인

import numpy as np
# 나이
print(X_train['age'][X_train['age']-np.floor(X_train['age']) != 0])

print(len(X_train['age'][X_train['age']-np.floor(X_train['age']) != 0]))
print(len(X_test['age'][X_test['age']-np.floor(X_test['age']) != 0]))

53      0.24
59      0.24
63      1.72
76      0.56
93      0.08
        ... 
3632    1.32
3662    0.08
3711    0.40
3768    1.80
3917    1.32
Name: age, Length: 91, dtype: float64
91
24


In [185]:
# 나이는 소수점을 버려서 저장
X_train['age'][X_train['age']-np.floor(X_train['age']) != 0].values

array([0.24, 0.24, 1.72, 0.56, 0.08, 1.48, 1.72, 1.88, 1.8 , 0.64, 0.8 ,
       1.64, 0.8 , 1.48, 1.64, 1.24, 1.32, 0.32, 1.72, 1.24, 0.56, 0.56,
       1.64, 0.48, 1.8 , 1.88, 1.4 , 1.08, 1.88, 1.08, 0.88, 1.08, 1.16,
       1.32, 1.56, 1.56, 1.16, 0.48, 1.64, 1.24, 1.32, 0.24, 1.64, 1.4 ,
       0.48, 0.32, 1.8 , 1.56, 1.8 , 0.16, 1.8 , 0.64, 1.8 , 1.08, 1.24,
       0.32, 1.48, 0.32, 1.08, 0.32, 1.48, 0.72, 0.56, 1.24, 1.72, 0.8 ,
       0.88, 1.08, 1.88, 1.08, 0.4 , 1.64, 0.88, 1.88, 1.64, 1.56, 0.24,
       1.72, 0.72, 0.88, 1.88, 1.72, 0.64, 0.8 , 1.8 , 1.48, 1.32, 0.08,
       0.4 , 1.8 , 1.32])

In [186]:
age_outliers = X_train['age'][X_train['age']-np.floor(X_train['age']) != 0].values

In [187]:
X_train['age'] = X_train['age'].replace(age_outliers, np.floor(age_outliers))

In [188]:
X_train['age'][53]

0.0

In [189]:
# 범주형 컬럼 값 확인
print(X_train['ever_married'].value_counts())
print(X_train['work_type'].value_counts())
print(X_train['Residence_type'].value_counts())
print(X_train['smoking_status'].value_counts())

Yes    2682
No     1405
Name: ever_married, dtype: int64
Private          2353
Self-employed     663
children          537
Govt_job          517
Never_worked       17
Name: work_type, dtype: int64
Urban    2074
Rural    2013
Name: Residence_type, dtype: int64
never smoked       1519
Unknown            1240
formerly smoked     709
smokes              619
Name: smoking_status, dtype: int64


In [190]:
# 범주형 컬럼 원핫인코딩
X_train = pd.get_dummies(X_train)
X_train.head()

X_test = pd.get_dummies(X_test)

In [191]:
X_train.head()

id   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0    575  13.0             0              0              98.65  20.1   
1  60533  23.0             0              0              91.95  23.0   
2  11935   9.0             0              0             110.97  17.7   
3  61291  28.0             0              0             169.49  27.2   
4  64534  25.0             0              0             104.66  23.9   

   gender_Female  gender_Male  ever_married_No  ever_married_Yes  ...  \
0              0            1                1                 0  ...   
1              1            0                1                 0  ...   
2              1            0                1                 0  ...   
3              0            1                0                 1  ...   
4              1            0                0                 1  ...   

   work_type_Never_worked  work_type_Private  work_type_Self-employed  \
0                       0                  0                        0   
1                       0                  1                        0   
2                       0                  0                        0   
3                       0                  1                        0   
4                       0                  1                        0   

   work_type_children  Residence_type_Rural  Residence_type_Urban  \
0                   1                     1                     0   
1                   0                     1                     0   
2                   1                     1                     0   
3                   0                     1                     0   
4                   0                     0                     1   

   smoking_status_Unknown  smoking_status_formerly smoked  \
0                       1                               0   
1                       1                               0   
2                       1                               0   
3                       1                               0   
4                       0                               0   

   smoking_status_never smoked  smoking_status_smokes  
0                            0                      0  
1                            0                      0  
2                            0                      0  
3                            0                      0  
4                            1                      0  

[5 rows x 21 columns]

In [149]:
# 스케일링 패스

In [194]:
# 1. 로지스틱 회귀

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train, y_train['stroke'])
print('훈련 정확도:', lr.score(X_train, y_train['stroke']))

pred1 = lr.predict(X_test)

print('테스트 정확도:', lr.score(X_test, y_test['stroke']))

훈련 정확도: 0.9508196721311475
테스트 정확도: 0.949119373776908


In [199]:
# 2. 랜덤 포레스트
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(max_depth=5)
rf.fit(X_train, y_train['stroke'])

print('훈련 정확도:', rf.score(X_train, y_train['stroke']))

pred2 = rf.predict(X_test)

print('테스트 정확도:', rf.score(X_test, y_test['stroke']))

훈련 정확도: 0.951309028627355
테스트 정확도: 0.9510763209393346


In [196]:
pred1, pred2

(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [197]:
len(pred2)

1022

In [210]:
list(pred2).count(1)

0

In [201]:
# 랜덤포레스트
result = pd.DataFrame({'id':X_test['id'], 'stroke':pred2})
#result.to_csv('result.csv', index=False)